// source_part_04/react/src/App.tsx
import JsonData from './edit-data.json'
import {ReactVisualEditor} from "./packages/ReactVisualEditor";
import './app.scss'
import {useState} from "react";
import {visualEditorBaseOption} from "./visual.config";
import {TestUseModelPage} from "./packages/utils/useModel";

function App() {

    const [formData, setFormData] = useState({} as any)

    return (
        <div className="app">
            <ReactVisualEditor formData={formData} option={visualEditorBaseOption} value={JsonData as any}>
                {{
                    username: () => {
                        return (
                            <div>
                                123
                            </div>
                        )
                    }
                }}
            </ReactVisualEditor>
            {/*<TestUseModelPage/>*/}
        </div>
    )
}

export default App

// demo-visual-editor/src/App.vue
<template>
  <div class="app">
    <visual-editor
      v-model="jsonData"
      :config="visualConfig"
      :formData="formData"
    />
  </div>
</template>
<script lang="ts">
import { defineComponent } from "vue";
import { VisualEditor } from "../src/packages/visual-editor";
// import { TestUseModel } from "../src/packages/utils/useModel";
import visualConfig from "./packages/visual.config";
import jsonData from "./jsonData.json";

export default defineComponent({
  name: "App",
  components: { VisualEditor },
  data() {
    return {
      visualConfig,
      jsonData: jsonData,
      formData: {
        username: "admin",
      },
    };
  },
});
</script>

<style lang="scss">
html,
body {
  margin: 0;
  padding: 0;
}
</style>
